(add-to-list 'load-path "~/.emacs.d/vendor")
(add-to-list 'load-path "~/.emacs.d/elpa")
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes/")
(setq custom-file "~/.emacs.d/mem/custom.el")
(load custom-file 'noerror)

(defun gtd ()
   (interactive)
   (find-file "~/Org/mike-maheu/gtd/gtd.org")
 )

(require 'package)
(add-to-list 'package-archives
    '("marmalade" .
      "http://marmalade-repo.org/packages/"))
(package-initialize)

(load "mem/theme")
(load "mem/env")
(load "mem/global")
(load "mem/defuns")
(load "mem/bindings")
(load "mem/tabs")
(load "mem/disabled")
(load "mem/fonts")
(load "mem/utf-8")
(load "mem/scratch")
(load "mem/grep")
(load "mem/diff")
(load "mem/ido")
(load "mem/dired")
(load "mem/recentf")
(load "mem/rectangle")
(load "mem/org")
(load "mem/zoom")
(load "mem/flymake")
(load "mem/javascript")
(load "mem/ri-emacs")
(load "mem/mac")
(load "mem/server-mode")
(load "mem/shell-mode")
(load "mem/ruby-mode")
(load "mem/rvm")
(load "mem/todotxt-mode")
(load "mem/private" 'noerror)
;; (load "mem/hl-line")
;; (load "mem/iswitchb")

(vendor 'expand-region 'er/expand-region)
(vendor 'multiple-cursors 'mc/edit-lines 'mc/mark-next-like-this 'mc/mark-previous-like-this 'mc/mark-all-like-this 'set-rectangular-region-anchor)
(vendor 'jump-char     'jump-char-forward 'jump-char-backward)
(vendor 'rinari)
(vendor 'textmate)
(vendor 'maxframe      'mf 'maximize-frame)
(vendor 'filladapt)
(vendor 'coffee-mode)
(vendor 'haml-mode)
(vendor 'sass-mode)
(vendor 'htmlize)
(vendor 'j2ee)
(vendor 'ack-and-a-half 'ack-and-a-half 'ack-and-a-half-same 'ack-and-a-half-find-file 'ack-and-a-half-find-file-same 'ack-and-a-half-interactive)
(vendor 'cdargs        'cv 'cdargs)
(vendor 'magit         'magit-status)
(vendor 'psvn          'svn-status)
(vendor 'js2-mode      'js2-mode)
(vendor 'markdown-mode 'markdown-mode 'gfm-mode)
(vendor 'textile-mode  'textile-mode)
(vendor 'csv-mode      'csv-mode)
(vendor 'yaml-mode     'yaml-mode)
(vendor 'rcodetools    'xmp)
(vendor 'yasnippet)
(vendor 'jekyll)
(vendor 'lua-mode      'lua-mode)
(vendor 'feature-mode)
(vendor 'mode-line-bell)
(vendor 'revbufs       'revbufs)
(vendor 'shell-pop)
(vendor 'mo-git-blame  'mo-git-blame-file 'mo-git-blame-current)
(vendor 'ace-jump-mode 'ace-jump-mode 'ace-jump-word-mode 'ace-jump-char-mode 'ace-jump-line-mode)
(vendor 'key-chord)
(vendor 'bundler       'bundle-open 'bundle-console 'bundle-install 'bundle-update 'bundle-check)
(vendor 'browse-kill-ring+ 'browse-kill-ring)
(vendor 'browse-kill-ring  'NEVERLOAD-browse-kill-ring)
(vendor 'dired-details 'dired-details-show 'dired-details-hide 'dired-details-toggle)
(vendor 'dired-details+)
(vendor 'powerline)


;; (vendor 'ruby-electric 'ruby-electric-mode)
;; (vendor 'auctex)
